package com.chronicare.platform.alerts.domain.model.valueobjects;

/**
 * Alert Source - origin of the alert
 */
public enum AlertSource {
    DEVICE("DEVICE", "Alert from IoT device or sensor"),
    SYSTEM("SYSTEM", "Alert generated by system rules or automated process"),
    MANUAL("MANUAL", "Alert manually created by user");

    private final String code;
    private final String description;

    AlertSource(String code, String description) {
        this.code = code;
        this.description = description;
    }

    public String getCode() {
        return code;
    }

    public String getDescription() {
        return description;
    }

    public static AlertSource fromCode(String code) {
        for (AlertSource source : values()) {
            if (source.code.equalsIgnoreCase(code)) {
                return source;
            }
        }
        throw new IllegalArgumentException("Invalid alert source code: " + code);
    }
}
